name: dart_funcoes_colecoes
description: Mudulo da cademia do flutter de funcoes e colecoes
version: 1.0.0
repository: https://github.com/LuannBarroso?tab=repositories

environment:
  sdk: ^3.3.3


dependencies:
   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
